---
title: "Lab 10"
author: "Lily Shkhyan"
date: "`r Sys.Date()`"
output: github_document
always_allow_html: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(repos = c(CRAN = "http://cran.rstudio.com"))
```

```{r instal packages}

if(!require(RSQLite)) install.packages(c("RSQLite"))
if(!require(DBI)) install.packages(c("DBI"))

library(RSQLite)
library(DBI)
```

## Data Setup
```{r}

# Initialize a temporary in memory database
con <- dbConnect(SQLite(), ":memory:")

# Download tables
actor <- read.csv("https://raw.githubusercontent.com/ivanceras/sakila/master/csv-sakila-db/actor.csv")
rental <- read.csv("https://raw.githubusercontent.com/ivanceras/sakila/master/csv-sakila-db/rental.csv")
customer <- read.csv("https://raw.githubusercontent.com/ivanceras/sakila/master/csv-sakila-db/customer.csv")
payment <- read.csv("https://raw.githubusercontent.com/ivanceras/sakila/master/csv-sakila-db/payment_p2007_01.csv")

# Copy data.frames to database
dbWriteTable(con, "actor", actor)
dbWriteTable(con, "rental", rental)
dbWriteTable(con, "customer", customer)
dbWriteTable(con, "payment", payment)
dbListTables(con)
```
```{sql, connection=con, output.var = "x1"}
PRAGMA table_info(actor)
```
```{r}
x1
```

```{sql, connection=con}
PRAGMA table_info(actor)
```
```{r}
dbGetQuery(con, "PRAGMA table_info(actor)"
)
```
# Exercise 1
```{r}
dbGetQuery(con, "
SELECT actor_id, first_name, last_name
FROM actor
ORDER BY last_name, first_name
LIMIT 15
")
```
Try in SQL 
```{sql , connection=con}
SELECT actor_id, first_name, last_name
FROM actor
ORDER BY last_name, first_name
```
# Exercise 2
```{r}
dbGetQuery(con, "
SELECT actor_id, first_name, last_name
FROM actor
WHERE last_name IN ('WILLIAMS', 'DAVIS')
ORDER BY last_name
")
```
# Exercise 3
```{r}
dbGetQuery(con, "PRAGMA table_info(rental)"
)
```
```{r}
dbGetQuery(con, "
SELECT distinct customer_id, rental_date
FROM rental
WHERE date(rental_date) = '2005-07-05'
")
```
```{r using count}
dbGetQuery(con, "
SELECT customer_id, Count(*) AS N
FROM rental
WHERE date(rental_date) = '2005-07-05'
GROUP BY customer_id
")
```

# Exercise 4
```{r}
dbGetQuery(con, "PRAGMA table_info(payment)"
)
```
### Exercise 4.1
```{r}
dbGetQuery(con, "
SELECT *
FROM payment
WHERE amount IN (1.99, 7.99, 9.99)
ORDER BY amount
")
```
### Exercise 4.2
```{r}
dbGetQuery(con, "
SELECT *
FROM payment
WHERE amount > 5
ORDER BY amount
")
```
### Exercise 4.3
```{r}
dbGetQuery(con, "
SELECT *
FROM payment
WHERE amount > 5 AND amount < 8
ORDER BY amount
")
```
# Exercise 5
```{r}
dbGetQuery(con, "PRAGMA table_info(customer)"
)
```
```{r}
dbGetQuery(con, "
SELECT c.customer_id, c.last_name, p.payment_id, p.amount
FROM customer AS c INNER JOIN payment AS p
  ON c.customer_id = p.customer_id
WHERE c.last_name == 'DAVIS'
")
```
# Exercise 6
### Exercise 6.1
```{r}
dbGetQuery(con, "
SELECT 
  COUNT(*) AS count
FROM rental
")
```
### Exercise 6.2
```{r}
dbGetQuery(con, "
SELECT customer_id, COUNT(*) AS count
FROM rental
GROUP BY customer_id
LIMIT 8
")
```
### Exercise 6.3
```{r}
dbGetQuery(con, "
SELECT customer_id, COUNT(*) AS count
FROM rental
GROUP BY customer_id
ORDER BY customer_id DESC
LIMIT 8
")
```
```{r}
dbGetQuery(con, "
SELECT customer_id, COUNT(*) AS count
FROM rental
GROUP BY customer_id
ORDER BY customer_id ASC
LIMIT 8
")
```
### Exercise 6.4
```{r}
dbGetQuery(con, "
SELECT customer_id, COUNT(*) AS count
FROM rental
GROUP BY customer_id
HAVING count > 39
LIMIT 8
")
```
# Exercise 7
```{r}
dbGetQuery(con, "
SELECT MAX(amount) AS maxpayment, 
       MIN(amount) AS minpayment,
       AVG(amount) AS avgpayment,
       SUM(amount) AS sumpayment
FROM payment
")
```
### Exercise 7.1
```{r}
dbGetQuery(con, "
SELECT customer_id, 
       MAX(amount) AS maxpayment, 
       MIN(amount) AS minpayment,
       AVG(amount) AS avgpayment,
       SUM(amount) AS sumpayment
FROM payment
GROUP BY customer_id
LIMIT 5
")
```
### Exercise 7.2
```{r}
dbGetQuery(con, "
SELECT customer_id, COUNT(*) AS N, 
       MAX(amount) AS maxpayment, 
       MIN(amount) AS minpayment,
       AVG(amount) AS avgpayment,
       SUM(amount) AS sumpayment
FROM payment
GROUP BY customer_id
HAVING N > 5
ORDER BY N
")
```
# Cleanup
```{r}
```