---
title: "Lab03"
author: "Lily"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Step 1: Read in the data
First download and then read in with data.table:fread()

```{r}
if (!file.exists("met_all.gz")) {
download.file("https://raw.githubusercontent.com/USCbiostats/data-science-data/master/02_met/met_all.gz", "met_all.gz", method="libcurl", timeout = 60) }
met <- data.table::fread("met_all.gz")
```

### Step 2: Check the dimensions, headers, footers. How many columns, rows are there?
```{r}
dim(met)
head(met)
tail(met)
```
### Step 3: Take a look at the variables.
```{r}
str(met)
```
#### Slep 4: Take a closer look at the key variables.
```{r}
table (met$year)
table (met$day)
table (met$hour)
summary(met$temp)
summary(met$elev)
summary(met$wind.sp)
```
```{r}
met[met$elev==9999.0] <- NA
summary(met$elev)
```
```{r}
met <- met[temp>-40]
met2 <- met[order(temp)]
head(met2)
```

### Step 5: Check the data against an external data source.
```{r}
met <- met[temp>-15]
met2 <- met[order(temp)]
head(met2)
```

### Step 6: Calculate summary statistics
```{r}
elev <- met[elev==max(elev, na.rm=TRUE)]
summary(elev)
cor(elev$temp, elev$wind.sp, use="complete")
cor(elev$temp, elev$hour, use="complete")
cor(elev$wind.sp, elev$day, use="complete")
cor(elev$wind.sp, elev$hour, use="complete")
cor(elev$temp, elev$day, use="complete")
```

### Step 7: Exploratory graphs

Look at key variables 

```{r}
hist(met$elev, breaks=100)
hist(met$temp)
hist(met$wind.sp)
```

```{r}
install.packages("leaflet") 
library(leaflet)
elev <- met[elev==max(elev)]
```
```{r}
leaflet(elev) %>% 
  addProviderTiles('OpenStreetMap') %>% 
  addCircles(lat=~lat,lng=~lon, opacity=1, fillOpacity=1, radius=100)
```

